export default {
  absoluteY: 2829,
  absoluteX: 76,
  boxes: [
    {
      type: "primaryBox",
      x: 471,
      y: 234,
      strokeColor: "orange5",
      hoverColor: "orange0",
      text: "Communication",
    },
    {
      type: "multiBox",
      x: 0,
      y: 114,
      width: 243,
      height: 153,
      fillColor: "orange0",
      text: "Product Teams",
    },
    {
      type: "multiBox",
      x: 0,
      y: 291,
      width: 243,
      height: 153,
      fillColor: "orange0",
      text: "Collaborating With Stakeholders",
    },
    {
      type: "multiBox",
      x: 0,
      y: 468,
      width: 243,
      height: 153,
      fillColor: "orange0",
      text: "Design Teams",
    },
    {
      type: "multiBox",
      x: 419,
      y: 468,
      width: 207,
      height: 153,
      fillColor: "orange0",
      text: "Interview Skills",
    },
    {
      type: "multiBox",
      x: 670,
      y: 468,
      width: 207,
      height: 153,
      fillColor: "orange0",
      text: "Design Portfolio",
    },
    {
      type: "multiBox",
      x: 921,
      y: 468,
      width: 207,
      height: 153,
      fillColor: "orange0",
      text: "Presentation Skills",
    },
    {
      type: "multiBox",
      x: 921,
      y: 177,
      width: 207,
      height: 153,
      fillColor: "orange0",
      text: "Methodologies",
    },
    {
      type: "multiBox",
      x: 921,
      y: 0,
      width: 207,
      height: 153,
      fillColor: "orange0",
      text: "Project Planning",
    },
    {
      type: "tertiaryBox",
      x: 16,
      y: 170,
      width: 211,
      fillColor: "orange0",
      strokeColor: "orange3",
      text: "Types of Product Teams",
      hoverColor: "orange1",
    },
    {
      type: "tertiaryBox",
      x: 16,
      y: 215,
      width: 211,
      fillColor: "orange0",
      strokeColor: "orange3",
      text: "Knowledge base",
      hoverColor: "orange1",
    },
    {
      type: "tertiaryBox",
      x: 16,
      y: 347,
      width: 211,
      fillColor: "orange0",
      strokeColor: "orange3",
      text: "Analysis and Alignment",
      hoverColor: "orange1",
    },
    {
      type: "tertiaryBox",
      x: 16,
      y: 392,
      width: 211,
      fillColor: "orange0",
      strokeColor: "orange3",
      text: "Pitching UX ideas",
      hoverColor: "orange1",
    },
    {
      type: "tertiaryBox",
      x: 16,
      y: 525,
      width: 211,
      fillColor: "orange0",
      strokeColor: "orange3",
      text: "Design Meetings",
      hoverColor: "orange1",
    },
    {
      type: "tertiaryBox",
      x: 16,
      y: 570,
      width: 211,
      fillColor: "orange0",
      strokeColor: "orange3",
      text: "Collaboration",
      hoverColor: "orange1",
    },
    {
      type: "tertiaryBox",
      x: 435,
      y: 525,
      width: 175,
      fillColor: "orange0",
      strokeColor: "orange3",
      text: "Beginner’s Guides",
      hoverColor: "orange1",
    },
    {
      type: "tertiaryBox",
      x: 435,
      y: 570,
      width: 175,
      fillColor: "orange0",
      strokeColor: "orange3",
      text: "Questions To Ask",
      hoverColor: "orange1",
    },
    {
      type: "tertiaryBox",
      x: 686,
      y: 525,
      width: 175,
      fillColor: "orange0",
      strokeColor: "orange3",
      text: "Best Practices",
      hoverColor: "orange1",
    },
    {
      type: "tertiaryBox",
      x: 686,
      y: 570,
      width: 175,
      fillColor: "orange0",
      strokeColor: "orange3",
      text: "Case Studies",
      hoverColor: "orange1",
    },
    {
      type: "tertiaryBox",
      x: 937,
      y: 525,
      width: 175,
      fillColor: "orange0",
      strokeColor: "orange3",
      text: "Beginner’s Guides",
      hoverColor: "orange1",
    },
    {
      type: "tertiaryBox",
      x: 937,
      y: 570,
      width: 175,
      fillColor: "orange0",
      strokeColor: "orange3",
      text: "Collecting Feedback",
      hoverColor: "orange1",
    },
    {
      type: "tertiaryBox",
      x: 937,
      y: 234,
      width: 175,
      fillColor: "orange0",
      strokeColor: "orange3",
      text: "Agile UX",
      hoverColor: "orange1",
    },
    {
      type: "tertiaryBox",
      x: 937,
      y: 279,
      width: 175,
      fillColor: "orange0",
      strokeColor: "orange3",
      text: "Lean UX",
      hoverColor: "orange1",
    },
    {
      type: "tertiaryBox",
      x: 937,
      y: 57,
      width: 175,
      fillColor: "orange0",
      strokeColor: "orange3",
      text: "Define OKRs",
      hoverColor: "orange1",
    },
    {
      type: "tertiaryBox",
      x: 937,
      y: 102,
      width: 175,
      fillColor: "orange0",
      strokeColor: "orange3",
      text: "Questions to ask",
      hoverColor: "orange1",
    },
    {
      type: "secondaryBox",
      x: 333,
      y: 379,
      width: 150,
      fillColor: "orange0",
      strokeColor: "orange4",
      text: "Soft Skills",
      hoverColor: "orange1",
    },
    {
      type: "secondaryBox",
      x: 670,
      y: 149,
      width: 160,
      fillColor: "orange0",
      strokeColor: "orange4",
      text: "Product Managment",
      hoverColor: "orange1",
    },
  ],
};
