export default {
  absoluteY: 665,
  absoluteX: 76,
  boxes: [
    {
      type: "primaryBox",
      x: 471,
      y: 140,
      strokeColor: "violet5",
      hoverColor: "violet0",
      text: "Design Research",
    },
    {
      type: "multiBox",
      x: 0,
      y: 0,
      width: 243,
      height: 333,
      fillColor: "violet0",
      text: "Discover (Primary Research)",
    },
    {
      type: "multiBox",
      x: 110,
      y: 386,
      width: 243,
      height: 153,
      fillColor: "violet0",
      text: "Types",
    },
    {
      type: "multiBox",
      x: 885,
      y: 0,
      width: 243,
      height: 243,
      fillColor: "violet0",
      text: "Explore and Experiment",
    },
    {
      type: "tertiaryBox",
      x: 16,
      y: 57,
      width: 211,
      fillColor: "violet0",
      strokeColor: "violet3",
      text: "Interviews",
      hoverColor: "violet1",
    },
    {
      type: "tertiaryBox",
      x: 16,
      y: 102,
      width: 211,
      fillColor: "violet0",
      strokeColor: "violet3",
      text: "Usability Test",
      hoverColor: "violet1",
    },
    {
      type: "tertiaryBox",
      x: 16,
      y: 147,
      width: 211,
      fillColor: "violet0",
      strokeColor: "violet3",
      text: "Surveys",
      hoverColor: "violet1",
    },
    {
      type: "tertiaryBox",
      x: 16,
      y: 192,
      width: 211,
      fillColor: "violet0",
      strokeColor: "violet3",
      text: "Contextual Inquiry",
      hoverColor: "violet1",
    },
    {
      type: "tertiaryBox",
      x: 16,
      y: 237,
      width: 211,
      fillColor: "violet0",
      strokeColor: "violet3",
      text: "Competitive Research",
      hoverColor: "violet1",
    },
    {
      type: "tertiaryBox",
      x: 16,
      y: 282,
      width: 211,
      fillColor: "violet0",
      strokeColor: "violet3",
      text: "SWOT analysis",
      hoverColor: "violet1",
    },
    {
      type: "tertiaryBox",
      x: 126,
      y: 443,
      width: 211,
      fillColor: "violet0",
      strokeColor: "violet3",
      text: "Qualitative Research",
      hoverColor: "violet1",
    },
    {
      type: "tertiaryBox",
      x: 126,
      y: 488,
      width: 211,
      fillColor: "violet0",
      strokeColor: "violet3",
      text: "Quantitative Research",
      hoverColor: "violet1",
    },
    {
      type: "tertiaryBox",
      x: 901,
      y: 57,
      width: 211,
      fillColor: "violet0",
      strokeColor: "violet3",
      text: "Task Analysis",
      hoverColor: "violet1",
    },
    {
      type: "tertiaryBox",
      x: 901,
      y: 102,
      width: 211,
      fillColor: "violet0",
      strokeColor: "violet3",
      text: "Analytics",
      hoverColor: "violet1",
    },
    {
      type: "tertiaryBox",
      x: 901,
      y: 147,
      width: 211,
      fillColor: "violet0",
      strokeColor: "violet3",
      text: "A / B Testing",
      hoverColor: "violet1",
    },
    {
      type: "tertiaryBox",
      x: 901,
      y: 192,
      width: 211,
      fillColor: "violet0",
      strokeColor: "violet3",
      text: "Card Sorting",
      hoverColor: "violet1",
    },
    {
      type: "secondaryBox",
      x: 913,
      y: 275,
      width: 187,
      fillColor: "violet0",
      strokeColor: "violet4",
      text: "Secondary Research",
      hoverColor: "violet1",
    },
    {
      type: "secondaryBox",
      x: 913,
      y: 331,
      width: 187,
      fillColor: "violet0",
      strokeColor: "violet4",
      text: "Research Tools",
      hoverColor: "violet1",
    },
    {
      type: "secondaryBox",
      x: 913,
      y: 387,
      width: 187,
      fillColor: "violet0",
      strokeColor: "violet4",
      text: "Research Repository",
      hoverColor: "violet1",
    },
    {
      type: "secondaryBox",
      x: 913,
      y: 443,
      width: 187,
      fillColor: "violet0",
      strokeColor: "violet4",
      text: "Research Planning",
      hoverColor: "violet1",
    },
    {
      type: "secondaryBox",
      x: 913,
      y: 499,
      width: 187,
      fillColor: "violet0",
      strokeColor: "violet4",
      text: "Analysis of Findings",
      hoverColor: "violet1",
    },
  ],
};
