export default {
  absoluteY: 2087,
  absoluteX: 76,
  boxes: [
    {
      type: "primaryBox",
      x: 471,
      y: 213,
      strokeColor: "lime5",
      hoverColor: "lime0",
      text: "User Interface",
    },
    {
      type: "multiBox",
      x: 0,
      y: 0,
      width: 207,
      height: 243,
      fillColor: "lime0",
      text: "Fundamentals",
    },
    {
      type: "multiBox",
      x: 0,
      y: 269,
      width: 207,
      height: 153,
      fillColor: "lime0",
      text: "Interface Inventory",
    },
    {
      type: "multiBox",
      x: 0,
      y: 444,
      width: 207,
      height: 198,
      fillColor: "lime0",
      text: "Design Guidelines",
    },
    {
      type: "multiBox",
      x: 274,
      y: 489,
      width: 207,
      height: 153,
      fillColor: "lime0",
      text: "Interactions",
    },
    {
      type: "multiBox",
      x: 624,
      y: 489,
      width: 207,
      height: 153,
      fillColor: "lime0",
      text: "Web Design",
    },
    {
      type: "multiBox",
      x: 921,
      y: 0,
      width: 207,
      height: 153,
      fillColor: "lime0",
      text: "Usability",
    },
    {
      type: "multiBox",
      x: 921,
      y: 200,
      width: 207,
      height: 198,
      fillColor: "lime0",
      text: "Accessebility",
    },
    {
      type: "multiBox",
      x: 921,
      y: 444,
      width: 207,
      height: 198,
      fillColor: "lime0",
      text: "Mobile UX Design",
    },
    {
      type: "tertiaryBox",
      x: 16,
      y: 57,
      width: 175,
      fillColor: "lime0",
      strokeColor: "lime3",
      text: "Colors Palette",
      hoverColor: "lime1",
    },
    {
      type: "tertiaryBox",
      x: 16,
      y: 102,
      width: 175,
      fillColor: "lime0",
      strokeColor: "lime3",
      text: "Typography Scale",
      hoverColor: "lime1",
    },
    {
      type: "tertiaryBox",
      x: 16,
      y: 147,
      width: 175,
      fillColor: "lime0",
      strokeColor: "lime3",
      text: "Grids and Spacings",
      hoverColor: "lime1",
    },
    {
      type: "tertiaryBox",
      x: 16,
      y: 192,
      width: 175,
      fillColor: "lime0",
      strokeColor: "lime3",
      text: "Icons and Assets",
      hoverColor: "lime1",
    },
    {
      type: "tertiaryBox",
      x: 16,
      y: 326,
      width: 175,
      fillColor: "lime0",
      strokeColor: "lime3",
      text: "Elements & Components",
      hoverColor: "lime1",
    },
    {
      type: "tertiaryBox",
      x: 16,
      y: 371,
      width: 175,
      fillColor: "lime0",
      strokeColor: "lime3",
      text: "UI Patterns",
      hoverColor: "lime1",
    },
    {
      type: "tertiaryBox",
      x: 16,
      y: 501,
      width: 175,
      fillColor: "lime0",
      strokeColor: "lime3",
      text: "Design Principles",
      hoverColor: "lime1",
    },
    {
      type: "tertiaryBox",
      x: 16,
      y: 546,
      width: 175,
      fillColor: "lime0",
      strokeColor: "lime3",
      text: "Documentation",
      hoverColor: "lime1",
    },
    {
      type: "tertiaryBox",
      x: 16,
      y: 591,
      width: 175,
      fillColor: "lime0",
      strokeColor: "lime3",
      text: "Tools",
      hoverColor: "lime1",
    },
    {
      type: "tertiaryBox",
      x: 290,
      y: 549,
      width: 175,
      fillColor: "lime0",
      strokeColor: "lime3",
      text: "Animation Principles",
      hoverColor: "lime1",
    },
    {
      type: "tertiaryBox",
      x: 290,
      y: 591,
      width: 175,
      fillColor: "lime0",
      strokeColor: "lime3",
      text: "Micro-Interactions",
      hoverColor: "lime1",
    },
    {
      type: "tertiaryBox",
      x: 640,
      y: 546,
      width: 175,
      fillColor: "lime0",
      strokeColor: "lime3",
      text: "HTML & CSS",
      hoverColor: "lime1",
    },
    {
      type: "tertiaryBox",
      x: 640,
      y: 591,
      width: 175,
      fillColor: "lime0",
      strokeColor: "lime3",
      text: "Responsive Layouts",
      hoverColor: "lime1",
    },
    {
      type: "tertiaryBox",
      x: 937,
      y: 57,
      width: 175,
      fillColor: "lime0",
      strokeColor: "lime3",
      text: "Rules & Guidelines",
      hoverColor: "lime1",
    },
    {
      type: "tertiaryBox",
      x: 937,
      y: 102,
      width: 175,
      fillColor: "lime0",
      strokeColor: "lime3",
      text: "Usability Issues",
      hoverColor: "lime1",
    },
    {
      type: "tertiaryBox",
      x: 937,
      y: 257,
      width: 175,
      fillColor: "lime0",
      strokeColor: "lime3",
      text: "Accessibility Guidelines",
      hoverColor: "lime1",
    },
    {
      type: "tertiaryBox",
      x: 937,
      y: 302,
      width: 175,
      fillColor: "lime0",
      strokeColor: "lime3",
      text: "Inclusive Design",
      hoverColor: "lime1",
    },
    {
      type: "tertiaryBox",
      x: 937,
      y: 347,
      width: 175,
      fillColor: "lime0",
      strokeColor: "lime3",
      text: "Tools and Checklist",
      hoverColor: "lime1",
    },
    {
      type: "tertiaryBox",
      x: 937,
      y: 501,
      width: 175,
      fillColor: "lime0",
      strokeColor: "lime3",
      text: "Best Practices",
      hoverColor: "lime1",
    },
    {
      type: "tertiaryBox",
      x: 937,
      y: 546,
      width: 175,
      fillColor: "lime0",
      strokeColor: "lime3",
      text: "IOS & Android",
      hoverColor: "lime1",
    },
    {
      type: "tertiaryBox",
      x: 937,
      y: 591,
      width: 175,
      fillColor: "lime0",
      strokeColor: "lime3",
      text: "Mobile UI Patterns",
      hoverColor: "lime1",
    },
    {
      type: "secondaryBox",
      x: 289,
      y: 141,
      width: 152,
      fillColor: "lime0",
      strokeColor: "lime4",
      text: "Design Hand-Off",
      hoverColor: "lime1",
    },
    {
      type: "secondaryBox",
      x: 289,
      y: 220,
      width: 152,
      fillColor: "lime0",
      strokeColor: "lime4",
      text: "Design Systems",
      hoverColor: "lime1",
    },
    {
      type: "secondaryBox",
      x: 289,
      y: 294,
      width: 152,
      fillColor: "lime0",
      strokeColor: "lime4",
      text: "Atomic Design",
      hoverColor: "lime1",
    },
  ],
};
