export default {
  absoluteY: 1304,
  absoluteX: 76,
  boxes: [
    {
      type: "primaryBox",
      x: 471,
      y: 225,
      strokeColor: "cyan5",
      hoverColor: "cyan0",
      text: "User Expirience",
    },
    {
      type: "multiBox",
      x: 0,
      y: 0,
      width: 207,
      height: 288,
      fillColor: "cyan0",
      text: "Empathize",
    },
    {
      type: "multiBox",
      x: 0,
      y: 310,
      width: 207,
      height: 108,
      fillColor: "cyan0",
      text: "Define",
    },
    {
      type: "multiBox",
      x: 0,
      y: 440,
      width: 207,
      height: 243,
      fillColor: "cyan0",
      text: "Ideate",
    },
    {
      type: "multiBox",
      x: 0,
      y: 440,
      width: 207,
      height: 243,
      fillColor: "cyan0",
      text: "Ideate",
    },
    {
      type: "multiBox",
      x: 255,
      y: 485,
      width: 207,
      height: 198,
      fillColor: "cyan0",
      text: "Prototype",
    },
    {
      type: "multiBox",
      x: 510,
      y: 530,
      width: 207,
      height: 153,
      fillColor: "cyan0",
      text: "Test and Iterate",
    },
    {
      type: "multiBox",
      x: 890,
      y: 0,
      width: 238,
      height: 153,
      fillColor: "cyan0",
      text: "Interaction Design",
    },
    {
      type: "multiBox",
      x: 890,
      y: 175,
      width: 238,
      height: 153,
      fillColor: "cyan0",
      text: "Visual Design",
    },
    {
      type: "multiBox",
      x: 890,
      y: 350,
      width: 238,
      height: 198,
      fillColor: "cyan0",
      text: "Agile UX",
    },
    {
      type: "tertiaryBox",
      x: 16,
      y: 57,
      width: 175,
      fillColor: "cyan0",
      strokeColor: "cyan3",
      text: "User Interviews",
      hoverColor: "cyan1",
    },
    {
      type: "tertiaryBox",
      x: 16,
      y: 102,
      width: 175,
      fillColor: "cyan0",
      strokeColor: "cyan3",
      text: "Surveys",
      hoverColor: "cyan1",
    },
    {
      type: "tertiaryBox",
      x: 16,
      y: 147,
      width: 175,
      fillColor: "cyan0",
      strokeColor: "cyan3",
      text: "Personas",
      hoverColor: "cyan1",
    },
    {
      type: "tertiaryBox",
      x: 16,
      y: 192,
      width: 175,
      fillColor: "cyan0",
      strokeColor: "cyan3",
      text: "Empathy Map",
      hoverColor: "cyan1",
    },
    {
      type: "tertiaryBox",
      x: 16,
      y: 237,
      width: 175,
      fillColor: "cyan0",
      strokeColor: "cyan3",
      text: "Customer Journey Map",
      hoverColor: "cyan1",
    },
    {
      type: "tertiaryBox",
      x: 16,
      y: 367,
      width: 175,
      fillColor: "cyan0",
      strokeColor: "cyan3",
      text: "Problem Statement",
      hoverColor: "cyan1",
    },
    {
      type: "tertiaryBox",
      x: 16,
      y: 497,
      width: 175,
      fillColor: "cyan0",
      strokeColor: "cyan3",
      text: "Brainstorming",
      hoverColor: "cyan1",
    },
    {
      type: "tertiaryBox",
      x: 16,
      y: 542,
      width: 175,
      fillColor: "cyan0",
      strokeColor: "cyan3",
      text: "Information Architecture",
      hoverColor: "cyan1",
    },
    {
      type: "tertiaryBox",
      x: 16,
      y: 587,
      width: 175,
      fillColor: "cyan0",
      strokeColor: "cyan3",
      text: "User Flows",
      hoverColor: "cyan1",
    },
    {
      type: "tertiaryBox",
      x: 16,
      y: 632,
      width: 175,
      fillColor: "cyan0",
      strokeColor: "cyan3",
      text: "Mind Mapping",
      hoverColor: "cyan1",
    },
    {
      type: "tertiaryBox",
      x: 271,
      y: 542,
      width: 175,
      fillColor: "cyan0",
      strokeColor: "cyan3",
      text: "Sketching",
      hoverColor: "cyan1",
    },
    {
      type: "tertiaryBox",
      x: 271,
      y: 587,
      width: 175,
      fillColor: "cyan0",
      strokeColor: "cyan3",
      text: "Wireframes",
      hoverColor: "cyan1",
    },
    {
      type: "tertiaryBox",
      x: 271,
      y: 632,
      width: 175,
      fillColor: "cyan0",
      strokeColor: "cyan3",
      text: "Prototypes",
      hoverColor: "cyan1",
    },
    {
      type: "tertiaryBox",
      x: 526,
      y: 587,
      width: 175,
      fillColor: "cyan0",
      strokeColor: "cyan3",
      text: "Usability Testing",
      hoverColor: "cyan1",
    },
    {
      type: "tertiaryBox",
      x: 526,
      y: 632,
      width: 175,
      fillColor: "cyan0",
      strokeColor: "cyan3",
      text: "Iterative Design Process",
      hoverColor: "cyan1",
    },
    {
      type: "tertiaryBox",
      x: 906,
      y: 57,
      width: 206,
      fillColor: "cyan0",
      strokeColor: "cyan3",
      text: "Human-Computer Interaction",
      hoverColor: "cyan1",
    },
    {
      type: "tertiaryBox",
      x: 906,
      y: 102,
      width: 206,
      fillColor: "cyan0",
      strokeColor: "cyan3",
      text: "Cognitive Psychology",
      hoverColor: "cyan1",
    },
    {
      type: "tertiaryBox",
      x: 906,
      y: 232,
      width: 206,
      fillColor: "cyan0",
      strokeColor: "cyan3",
      text: "Visual Design Principles",
      hoverColor: "cyan1",
    },
    {
      type: "tertiaryBox",
      x: 906,
      y: 277,
      width: 206,
      fillColor: "cyan0",
      strokeColor: "cyan3",
      text: "Visual Hierarchy",
      hoverColor: "cyan1",
    },
    {
      type: "tertiaryBox",
      x: 906,
      y: 407,
      width: 206,
      fillColor: "cyan0",
      strokeColor: "cyan3",
      text: "Lean vs Agile UX",
      hoverColor: "cyan1",
    },
    {
      type: "tertiaryBox",
      x: 906,
      y: 452,
      width: 206,
      fillColor: "cyan0",
      strokeColor: "cyan3",
      text: "Jobs-To-Be-Done",
      hoverColor: "cyan1",
    },
    {
      type: "tertiaryBox",
      x: 906,
      y: 497,
      width: 206,
      fillColor: "cyan0",
      strokeColor: "cyan3",
      text: "User Stories",
      hoverColor: "cyan1",
    },
    {
      type: "secondaryBox",
      x: 284,
      y: 279,
      width: 150,
      fillColor: "cyan0",
      strokeColor: "cyan4",
      text: "Design Thinking",
      hoverColor: "cyan1",
    },
    {
      type: "secondaryBox",
      x: 694,
      y: 164,
      width: 150,
      fillColor: "cyan0",
      strokeColor: "cyan4",
      text: "UX Benchmarking",
      hoverColor: "cyan1",
    },
    {
      type: "secondaryBox",
      x: 694,
      y: 299,
      width: 150,
      fillColor: "cyan0",
      strokeColor: "cyan4",
      text: "Content Strategy",
      hoverColor: "cyan1",
    },
    {
      type: "secondaryBox",
      x: 694,
      y: 361,
      width: 150,
      fillColor: "cyan0",
      strokeColor: "cyan4",
      text: "UX Storytelling",
      hoverColor: "cyan1",
    },
  ],
};
